sudo: false
language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
install:
  - pip install -U poetry tox-travis
env:
  - TOXENV="py3, flake8"
script: tox
